export const RULE_EVALUATION_REASON = {
  RULE_PASSED: 'RULE_PASSED',
  RULE_FAILED: 'RULE_FAILED',
  RULE_CONFIGURATION_ERROR: 'RULE_CONFIGURATION_ERROR',
} as const

export type RuleEvaluationReasonCode = (typeof RULE_EVALUATION_REASON)[keyof typeof RULE_EVALUATION_REASON]

export const RESERVATION_RULE = {
  CAMPAIGN: 'RESERVATION_CAMPAIGN',
  BUSINESS: 'RESERVATION_BUSINESS',
  DATE_PERIOD: 'RESERVATION_DATE_PERIOD',
  WEEKDAY: 'RESERVATION_WEEKDAY',
  TIME: 'RESERVATION_TIME',
  BOUNDARY: 'RESERVATION_BOUNDARY',
  TIMEZONE: 'RESERVATION_TIMEZONE',
  BOOKING_METHOD: 'RESERVATION_BOOKING_METHOD',
  VISIT_C_APPROVAL: 'RESERVATION_VISIT_C_APPROVAL',
  STATUS: 'RESERVATION_STATUS',
  LEAD_TIME: 'RESERVATION_LEAD_TIME',
  BLACKOUT: 'RESERVATION_BLACKOUT',
  CAMPAIGN_STATUS: 'RESERVATION_CAMPAIGN_STATUS',
  CAPACITY: 'RESERVATION_CAPACITY',
} as const

export type ReservationRuleCode = (typeof RESERVATION_RULE)[keyof typeof RESERVATION_RULE]

export const RESERVATION_CORRECTION = {
  CAMPAIGN_REVIEW: 'CAMPAIGN_REVIEW',
  WRONG_BUSINESS: 'WRONG_BUSINESS',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_WEEKDAY: 'INVALID_WEEKDAY',
  INVALID_TIME: 'INVALID_TIME',
  INVALID_BOUNDARY: 'INVALID_BOUNDARY',
  CLARIFY_TIMEZONE: 'CLARIFY_TIMEZONE',
  WRONG_BOOKING_METHOD: 'WRONG_BOOKING_METHOD',
  APPROVAL_REVIEW: 'APPROVAL_REVIEW',
  COMPLETE_BOOKING: 'COMPLETE_BOOKING',
  INSUFFICIENT_LEAD_TIME: 'INSUFFICIENT_LEAD_TIME',
  BLACKOUT_DATE: 'BLACKOUT_DATE',
  CAMPAIGN_CLOSED: 'CAMPAIGN_CLOSED',
  CAPACITY_REVIEW: 'CAPACITY_REVIEW',
  CONFIGURATION_REVIEW: 'CONFIGURATION_REVIEW',
} as const

export type ReservationCorrectionCode = (typeof RESERVATION_CORRECTION)[keyof typeof RESERVATION_CORRECTION]
