export const MESSAGING_REASON = {
  OUTBOUND_INTENT_CREATED: 'OUTBOUND_INTENT_CREATED',
  OUTBOUND_INTENT_CLAIMED: 'OUTBOUND_INTENT_CLAIMED',
  HUMAN_OWNERSHIP_ACTIVE: 'HUMAN_OWNERSHIP_ACTIVE',
  TEMPLATE_NOT_ACTIVE: 'TEMPLATE_NOT_ACTIVE',
  TEMPLATE_VARIABLE_MISSING: 'TEMPLATE_VARIABLE_MISSING',
  TEMPLATE_VARIABLE_UNKNOWN: 'TEMPLATE_VARIABLE_UNKNOWN',
  TEMPLATE_VARIABLE_FORBIDDEN: 'TEMPLATE_VARIABLE_FORBIDDEN',
  TEMPLATE_SYNTAX_INVALID: 'TEMPLATE_SYNTAX_INVALID',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  SYSTEM_NOTICE_NOT_ALLOWLISTED: 'SYSTEM_NOTICE_NOT_ALLOWLISTED',
  OPERATOR_OWNERSHIP_REQUIRED: 'OPERATOR_OWNERSHIP_REQUIRED',
  OWNERSHIP_CONFLICT: 'OWNERSHIP_CONFLICT',
  OWNERSHIP_RELEASED: 'OWNERSHIP_RELEASED',
} as const

export type MessagingReasonCode = (typeof MESSAGING_REASON)[keyof typeof MESSAGING_REASON]
