export const WORKFLOW_TRANSITION_REASON = {
  APPROVED: 'WORKFLOW_TRANSITION_APPROVED',
  NOT_ALLOWED: 'WORKFLOW_TRANSITION_NOT_ALLOWED',
  GUARD_FAILED: 'WORKFLOW_TRANSITION_GUARD_FAILED',
  STALE_VERSION: 'WORKFLOW_STALE_VERSION',
  STALE_EVENT: 'WORKFLOW_STALE_EVENT',
  AUTOMATION_PAUSED: 'WORKFLOW_AUTOMATION_PAUSED',
  HUMAN_OWNERSHIP_ACTIVE: 'WORKFLOW_HUMAN_OWNERSHIP_ACTIVE',
  CAMPAIGN_CLOSED: 'WORKFLOW_CAMPAIGN_CLOSED',
  WEAK_MATCH_CANNOT_BIND: 'WORKFLOW_WEAK_MATCH_CANNOT_BIND',
  VISIT_C_APPROVAL_REQUIRED: 'WORKFLOW_VISIT_C_APPROVAL_REQUIRED',
  RESERVATION_REVALIDATION_REQUIRED: 'WORKFLOW_RESERVATION_REVALIDATION_REQUIRED',
  DUPLICATE_GUIDELINE_NOT_AUTHORIZED: 'WORKFLOW_DUPLICATE_GUIDELINE_NOT_AUTHORIZED',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_SCOPE_CONFLICT: 'WORKFLOW_SCOPE_CONFLICT',
  WORKFLOW_INITIALIZED: 'WORKFLOW_INITIALIZED',
  CORRECTION_APPLIED: 'WORKFLOW_CORRECTION_APPLIED',
  CORRECTION_NOT_AUTHORIZED: 'WORKFLOW_CORRECTION_NOT_AUTHORIZED',
  CORRECTION_TARGET_INVALID: 'WORKFLOW_CORRECTION_TARGET_INVALID',
  CORRECTION_EVENT_NOT_CURRENT: 'WORKFLOW_CORRECTION_EVENT_NOT_CURRENT',
  SIDE_EFFECT_INVALIDATED: 'WORKFLOW_SIDE_EFFECT_INVALIDATED',
  DELIVERED_GUIDELINE_INVALIDATED: 'WORKFLOW_DELIVERED_GUIDELINE_INVALIDATED',
  PAUSE_NOT_AUTHORIZED: 'WORKFLOW_PAUSE_NOT_AUTHORIZED',
  PAUSE_ALREADY_ACTIVE: 'WORKFLOW_PAUSE_ALREADY_ACTIVE',
  PAUSE_NOT_ACTIVE: 'WORKFLOW_PAUSE_NOT_ACTIVE',
  PAUSE_ACTIVATED: 'WORKFLOW_PAUSE_ACTIVATED',
  PAUSE_DEACTIVATED: 'WORKFLOW_PAUSE_DEACTIVATED',
} as const

export type WorkflowTransitionReasonCode = (typeof WORKFLOW_TRANSITION_REASON)[keyof typeof WORKFLOW_TRANSITION_REASON]

export const WORKFLOW_AUDIT_ACTION = {
  CREATED: 'WORKFLOW_CREATED',
  TRANSITIONED: 'WORKFLOW_TRANSITIONED',
  TRANSITION_REJECTED: 'WORKFLOW_TRANSITION_REJECTED',
  CORRECTED: 'CORRECTION_APPLIED',
  PAUSED: 'AUTOMATION_PAUSED',
  RESUMED: 'AUTOMATION_RESUMED',
  INCIDENT_CREATED: 'WORKFLOW_INCIDENT_CREATED',
} as const

export type WorkflowAuditAction = (typeof WORKFLOW_AUDIT_ACTION)[keyof typeof WORKFLOW_AUDIT_ACTION]
