export const CONVERSATION_REASON = {
  OBSERVED: 'CONVERSATION_OBSERVED',
  PARTICIPANT_BOUND: 'CONVERSATION_PARTICIPANT_BOUND',
  PARTICIPANT_REBOUND: 'CONVERSATION_PARTICIPANT_REBOUND',
  WORKFLOW_BOUND: 'CONVERSATION_WORKFLOW_BOUND',
  WORKFLOW_REBOUND: 'CONVERSATION_WORKFLOW_REBOUND',
  CLOSED_BY_PROVIDER: 'CONVERSATION_CLOSED_BY_PROVIDER',
  DELETED_BY_PROVIDER: 'CONVERSATION_DELETED_BY_PROVIDER',
  MARKED_AMBIGUOUS: 'CONVERSATION_MARKED_AMBIGUOUS',
  AMBIGUITY_RESOLVED: 'CONVERSATION_AMBIGUITY_RESOLVED',
} as const

export type ConversationReasonCode = (typeof CONVERSATION_REASON)[keyof typeof CONVERSATION_REASON]

export const CONVERSATION_ERROR = {
  PROVIDER_INVALID: 'CONVERSATION_PROVIDER_INVALID',
  THREAD_ID_INVALID: 'CONVERSATION_THREAD_ID_INVALID',
  NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  PARTICIPANT_REQUIRED: 'CONVERSATION_PARTICIPANT_REQUIRED',
  BINDING_UNCHANGED: 'CONVERSATION_BINDING_UNCHANGED',
  REASON_CODE_INVALID: 'CONVERSATION_REASON_CODE_INVALID',
  EVIDENCE_CATEGORY_INVALID: 'CONVERSATION_EVIDENCE_CATEGORY_INVALID',
  ACTOR_REFERENCE_INVALID: 'CONVERSATION_ACTOR_REFERENCE_INVALID',
  TERMINAL_STATE: 'CONVERSATION_TERMINAL_STATE',
  MESSAGE_ID_INVALID: 'INBOUND_MESSAGE_ID_INVALID',
  MESSAGE_BODY_REQUIRED: 'INBOUND_MESSAGE_BODY_REQUIRED',
  MESSAGE_BODY_TOO_LONG: 'INBOUND_MESSAGE_BODY_TOO_LONG',
  MESSAGE_PURPOSE_INVALID: 'INBOUND_MESSAGE_PURPOSE_INVALID',
  MESSAGE_TIME_INVALID: 'INBOUND_MESSAGE_TIME_INVALID',
  EVIDENCE_WORKFLOW_MISMATCH: 'SECRET_COMMENT_EVIDENCE_WORKFLOW_MISMATCH',
  EVIDENCE_SCREENSHOT_REQUIRED: 'SECRET_COMMENT_EVIDENCE_SCREENSHOT_REQUIRED',
  EVIDENCE_STALE_EVENT: 'SECRET_COMMENT_EVIDENCE_STALE_EVENT',
} as const

export type ConversationErrorCode = (typeof CONVERSATION_ERROR)[keyof typeof CONVERSATION_ERROR]

export class ConversationServiceError extends Error {
  override readonly name = 'ConversationServiceError'
  constructor(readonly reasonCode: ConversationErrorCode) {
    super(`conversation action rejected: ${reasonCode}`)
  }
}
