export const HUMAN_REVIEW_OPERATION_REASON = {
  EPISODE_CREATED: 'HUMAN_REVIEW_EPISODE_CREATED',
  HOLDING_QUEUED: 'HUMAN_REVIEW_HOLDING_QUEUED',
  ASSIGNED: 'HUMAN_REVIEW_ASSIGNED',
  RELEASED: 'HUMAN_REVIEW_RELEASED',
  RESOLUTION_RECORDED: 'HUMAN_REVIEW_RESOLUTION_RECORDED',
  RETURNED_TO_AUTOMATION: 'HUMAN_REVIEW_RETURNED_TO_AUTOMATION',
  TASK_NOT_FOUND: 'HUMAN_REVIEW_TASK_NOT_FOUND',
  TASK_NOT_OPEN: 'HUMAN_REVIEW_TASK_NOT_OPEN',
  OWNERSHIP_CONFLICT: 'HUMAN_REVIEW_OWNERSHIP_CONFLICT',
  OPERATOR_NOT_AUTHORIZED: 'HUMAN_REVIEW_OPERATOR_NOT_AUTHORIZED',
  RESOLUTION_CODE_INVALID: 'HUMAN_REVIEW_RESOLUTION_CODE_INVALID',
  RESOLUTION_REASON_REQUIRED: 'HUMAN_REVIEW_RESOLUTION_REASON_REQUIRED',
  RETURN_ACTION_NOT_ALLOWED: 'HUMAN_REVIEW_RETURN_ACTION_NOT_ALLOWED',
  CAMPAIGN_NOT_ACTIVE: 'HUMAN_REVIEW_CAMPAIGN_NOT_ACTIVE',
  ACTIVE_PAUSE: 'HUMAN_REVIEW_ACTIVE_AUTOMATION_PAUSE',
  OTHER_OPEN_TASK: 'HUMAN_REVIEW_OTHER_OPEN_TASK',
  RESUME_STATE_INVALID: 'HUMAN_REVIEW_RESUME_STATE_INVALID',
} as const

export type HumanReviewOperationReasonCode =
  (typeof HUMAN_REVIEW_OPERATION_REASON)[keyof typeof HUMAN_REVIEW_OPERATION_REASON]
