export const HUMAN_REVIEW_REASON = {
  PARTICIPANT_REQUESTED_PERSON: 'PARTICIPANT_REQUESTED_PERSON',
  COMPLAINT: 'COMPLAINT',
  IDENTITY_AMBIGUOUS: 'IDENTITY_AMBIGUOUS',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT',
  MISSING_SCORE_OR_PROVIDER_OUTAGE: 'MISSING_SCORE_OR_PROVIDER_OUTAGE',
  BORDERLINE_SELECTION: 'BORDERLINE_SELECTION',
  SELECTION_REVOKED: 'SELECTION_REVOKED',
  SHIPPING_CHANGE_AFTER_CUTOFF: 'SHIPPING_CHANGE_AFTER_CUTOFF',
  SUSPICIOUS_SCREENSHOT: 'SUSPICIOUS_SCREENSHOT',
  VISIT_C_APPROVAL_REVOKED: 'VISIT_C_APPROVAL_REVOKED',
  GUIDELINE_MAY_HAVE_BEEN_SENT_PREMATURELY: 'GUIDELINE_MAY_HAVE_BEEN_SENT_PREMATURELY',
  REPEATED_FAILED_VERIFICATION: 'REPEATED_FAILED_VERIFICATION',
  PERSONAL_DATA_REQUEST: 'PERSONAL_DATA_REQUEST',
  UNKNOWN_INTENT_AFTER_RETRIES: 'UNKNOWN_INTENT_AFTER_RETRIES',
  SYSTEM_SECURITY_ALERT: 'SYSTEM_SECURITY_ALERT',
} as const

export type HumanReviewReasonCode = (typeof HUMAN_REVIEW_REASON)[keyof typeof HUMAN_REVIEW_REASON]
