/** Canonical authorization actions shared by transport-neutral admin services and operator clients. */
export const ADMIN_ACTIONS = [
  'operations.overview.read',
  'participants.search',
  'participants.timeline.read',
  'human_tasks.queue.read',
  'human_tasks.assign',
  'human_tasks.resolve',
  'human_tasks.resume_automation',
  'overrides.approve',
  'campaigns.read',
  'campaigns.configure',
  'selection_rules.publish',
  'reservation_rules.publish',
  'business_approvals.queue.read',
  'business_approvals.record',
  'message_templates.read',
  'message_templates.publish',
  'guidelines.read',
  'guidelines.publish',
  'notifications.history.read',
  'deduplication.history.read',
  'failed_jobs.read',
  'failed_jobs.retry',
  'integrations.health.read',
  'audit_logs.read',
  'privacy_requests.read',
  'retention_schedules.publish',
  'legal_holds.manage',
  'users_roles.read',
  'users_roles.manage',
  'automation_pauses.read',
  'automation_pauses.activate',
  'automation_pauses.resume',
  'ai_cost.read',
  'sensitive_values.reveal',
  'sensitive_data.export',
] as const

export type AdminAction = (typeof ADMIN_ACTIONS)[number]
