export const GUIDELINE_BLOCK = {
  READY: 'GUIDELINE_READY',
  AUTOMATION_PAUSED: 'AUTOMATION_PAUSED',
  HUMAN_OWNERSHIP_ACTIVE: 'HUMAN_OWNERSHIP_ACTIVE',
  CAMPAIGN_NOT_ACTIVE: 'CAMPAIGN_NOT_ACTIVE',
  NOT_SELECTED: 'NOT_SELECTED',
  NO_ACTIVE_GUIDELINE_VERSION: 'NO_ACTIVE_GUIDELINE_VERSION',
  VERSION_ALREADY_DELIVERED: 'VERSION_ALREADY_DELIVERED',
  SHIPPING_ADDRESS_NOT_VALID: 'SHIPPING_ADDRESS_NOT_VALID',
  SHIPPING_PREREQUISITES_NOT_MET: 'SHIPPING_PREREQUISITES_NOT_MET',
  CONSENT_NOT_CURRENT: 'CONSENT_NOT_CURRENT',
  PAYBACK_PREREQUISITES_NOT_MET: 'PAYBACK_PREREQUISITES_NOT_MET',
  SCREENSHOT_NOT_SAFE: 'SCREENSHOT_NOT_SAFE',
  CRITICAL_FIELDS_NOT_EXTRACTED: 'CRITICAL_FIELDS_NOT_EXTRACTED',
  BUSINESS_APPROVAL_NOT_CURRENT: 'BUSINESS_APPROVAL_NOT_CURRENT',
  BUSINESS_APPROVAL_EXPIRED: 'BUSINESS_APPROVAL_EXPIRED',
  RESERVATION_NOT_VALID: 'RESERVATION_NOT_VALID',
} as const

export type GuidelineBlockCode = (typeof GUIDELINE_BLOCK)[keyof typeof GUIDELINE_BLOCK]
