export const IDENTITY_RESOLUTION_REASON = {
  VERIFICATION_TOKEN: 'IDENTITY_VERIFICATION_TOKEN',
  PHONE_CAMPAIGN_NAME: 'IDENTITY_PHONE_CAMPAIGN_NAME',
  PHONE_CAMPAIGN_AMBIGUOUS: 'IDENTITY_PHONE_CAMPAIGN_AMBIGUOUS',
  NAME_ONLY_WEAK: 'IDENTITY_NAME_ONLY_WEAK',
  MULTIPLE_CAMPAIGNS: 'IDENTITY_MULTIPLE_CAMPAIGNS',
  SECRET_COMMENT_SUPPORTING_ONLY: 'IDENTITY_SECRET_COMMENT_SUPPORTING_ONLY',
  BLOG_CAMPAIGN_WEAK: 'IDENTITY_BLOG_CAMPAIGN_WEAK',
  BLOG_CAMPAIGN_STRONG: 'IDENTITY_BLOG_CAMPAIGN_STRONG',
  MULTIPLE_CANDIDATES: 'IDENTITY_MULTIPLE_CANDIDATES',
  NO_CANDIDATE: 'IDENTITY_NO_CANDIDATE',
  PARTICIPANT_LINK_CONFLICT: 'IDENTITY_PARTICIPANT_LINK_CONFLICT',
  MATCHING_EVIDENCE_INVALID: 'IDENTITY_MATCHING_EVIDENCE_INVALID',
  TOKEN_UNKNOWN: 'IDENTITY_TOKEN_UNKNOWN',
  TOKEN_EXPIRED: 'IDENTITY_TOKEN_EXPIRED',
  TOKEN_REUSED: 'IDENTITY_TOKEN_REUSED',
  TOKEN_CONFIGURATION_INVALID: 'IDENTITY_TOKEN_CONFIGURATION_INVALID',
  CAMPAIGN_DISAMBIGUATION_REQUIRED: 'IDENTITY_CAMPAIGN_DISAMBIGUATION_REQUIRED',
  ADDITIONAL_VERIFICATION_REQUIRED: 'IDENTITY_ADDITIONAL_VERIFICATION_REQUIRED',
} as const

export type IdentityResolutionReasonCode = (typeof IDENTITY_RESOLUTION_REASON)[keyof typeof IDENTITY_RESOLUTION_REASON]
