export const WORKFLOW_SIDE_EFFECT = {
  QUEUE_APPLICATION_REQUEST_MESSAGE: 'QUEUE_APPLICATION_REQUEST_MESSAGE',
  RUN_APPLICATION_RECONCILIATION: 'RUN_APPLICATION_RECONCILIATION',
  BEGIN_IDENTITY_MATCHING: 'BEGIN_IDENTITY_MATCHING',
  PERSIST_CHANNEL_LINK: 'PERSIST_CHANNEL_LINK',
  CREATE_HUMAN_TASK: 'CREATE_HUMAN_TASK',
  LOAD_SELECTION_RULE: 'LOAD_SELECTION_RULE',
  ROUTE_CAMPAIGN: 'ROUTE_CAMPAIGN',
  APPLY_SELECTION_FAILURE_POLICY: 'APPLY_SELECTION_FAILURE_POLICY',
  PAUSE_SELECTION_AUTOMATION: 'PAUSE_SELECTION_AUTOMATION',
  SEND_TERMS_AND_CONSENT_REQUEST: 'SEND_TERMS_AND_CONSENT_REQUEST',
  EVALUATE_GUIDELINE_READINESS: 'EVALUATE_GUIDELINE_READINESS',
  STOP_PROGRESSION: 'STOP_PROGRESSION',
  PAUSE_AND_REVIEW: 'PAUSE_AND_REVIEW',
  SEND_APPROVAL_PENDING_MESSAGE_ONLY: 'SEND_APPROVAL_PENDING_MESSAGE_ONLY',
  QUEUE_BOOKING_INSTRUCTIONS_ONCE: 'QUEUE_BOOKING_INSTRUCTIONS_ONCE',
  STOP_AUTOMATION_AND_CREATE_REVIEW: 'STOP_AUTOMATION_AND_CREATE_REVIEW',
  VALIDATE_SHIPPING_FIELDS: 'VALIDATE_SHIPPING_FIELDS',
  SEND_RESERVATION_INSTRUCTIONS_ONCE: 'SEND_RESERVATION_INSTRUCTIONS_ONCE',
  QUEUE_OCR: 'QUEUE_OCR',
  RUN_RESERVATION_RULES: 'RUN_RESERVATION_RULES',
  SEND_RESERVATION_CORRECTION: 'SEND_RESERVATION_CORRECTION',
  REVOKE_GUIDELINE_READINESS: 'REVOKE_GUIDELINE_READINESS',
  REVALIDATE_AND_REVOKE_PRIOR_READINESS: 'REVALIDATE_AND_REVOKE_PRIOR_READINESS',
  CREATE_OUTBOX_INTENT: 'CREATE_OUTBOX_INTENT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECORD_DELIVERY: 'RECORD_DELIVERY',
  PAUSE_AUTOMATION: 'PAUSE_AUTOMATION',
  SEND_HOLDING_MESSAGE: 'SEND_HOLDING_MESSAGE',
  RESUME_FROM_CURRENT_STATE: 'RESUME_FROM_CURRENT_STATE',
  REEVALUATE_GUIDELINE_READINESS: 'REEVALUATE_GUIDELINE_READINESS',
  CREATE_CRITICAL_INCIDENT: 'CREATE_CRITICAL_INCIDENT',
} as const

export type WorkflowSideEffectCode = (typeof WORKFLOW_SIDE_EFFECT)[keyof typeof WORKFLOW_SIDE_EFFECT]

export const ALL_WORKFLOW_SIDE_EFFECTS: readonly WorkflowSideEffectCode[] = Object.freeze(
  Object.values(WORKFLOW_SIDE_EFFECT),
)

export const isWorkflowSideEffectCode = (value: string): value is WorkflowSideEffectCode => {
  const codes: readonly string[] = ALL_WORKFLOW_SIDE_EFFECTS
  return codes.includes(value)
}
