export const APPLICATION_SYNC_REASON = {
  UNSUPPORTED_EVENT: 'APPLICATION_SYNC_UNSUPPORTED_EVENT',
  UNSUPPORTED_STATUS: 'APPLICATION_SYNC_UNSUPPORTED_STATUS',
  INVALID_SOURCE_VERSION: 'APPLICATION_SYNC_INVALID_SOURCE_VERSION',
  INVALID_BLOGGER_RANKING: 'APPLICATION_SYNC_INVALID_BLOGGER_RANKING',
  UPDATE_WITHOUT_CREATE: 'APPLICATION_SYNC_UPDATE_WITHOUT_CREATE',
  SOURCE_MISMATCH: 'APPLICATION_SYNC_SOURCE_MISMATCH',
  RECONCILIATION_NOT_FOUND: 'APPLICATION_RECONCILIATION_NOT_FOUND',
  RECONCILIATION_NOT_DUE: 'APPLICATION_RECONCILIATION_NOT_DUE',
  RECONCILIATION_SOURCE_MISMATCH: 'APPLICATION_RECONCILIATION_SOURCE_MISMATCH',
  RECONCILIATION_SOURCE_FAILED: 'APPLICATION_RECONCILIATION_SOURCE_FAILED',
} as const

export type ApplicationSyncReasonCode = (typeof APPLICATION_SYNC_REASON)[keyof typeof APPLICATION_SYNC_REASON]
