export const OCR_ORCHESTRATION_REASON = {
  REQUEST_CONFLICT: 'OCR_REQUEST_ID_CONTENT_MISMATCH',
  PROVIDER_TIMEOUT: 'OCR_PROVIDER_TIMEOUT',
  PROVIDER_INVALID_RESULT: 'OCR_PROVIDER_INVALID_RESULT',
  PROVIDER_UNAVAILABLE: 'OCR_PROVIDER_UNAVAILABLE',
  PROVIDER_REFUSED: 'OCR_PROVIDER_REFUSED',
  PROVIDER_DISAGREEMENT: 'OCR_PROVIDER_DISAGREEMENT',
  PROVIDER_COMPARISON_UNAVAILABLE: 'OCR_PROVIDER_COMPARISON_UNAVAILABLE',
  PROVIDER_CASCADE_EXHAUSTED: 'OCR_PROVIDER_CASCADE_EXHAUSTED',
} as const
