export const BUSINESS_APPROVAL_REASON = {
  APPROVED_CURRENT: 'APPROVED_CURRENT',
  APPROVAL_NOT_REQUIRED_INVALID_FOR_VISIT_C: 'APPROVAL_NOT_REQUIRED_INVALID_FOR_VISIT_C',
  APPROVAL_NOT_REQUESTED: 'APPROVAL_NOT_REQUESTED',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  APPROVAL_REVOKED: 'APPROVAL_REVOKED',
  APPROVAL_HUMAN_REVIEW_REQUIRED: 'APPROVAL_HUMAN_REVIEW_REQUIRED',
  APPROVAL_VERSION_NOT_CURRENT: 'APPROVAL_VERSION_NOT_CURRENT',
  APPROVAL_SOURCE_NOT_AUTHORIZED: 'APPROVAL_SOURCE_NOT_AUTHORIZED',
  APPROVAL_SCOPE_MISMATCH: 'APPROVAL_SCOPE_MISMATCH',
} as const

export type BusinessApprovalReasonCode = (typeof BUSINESS_APPROVAL_REASON)[keyof typeof BUSINESS_APPROVAL_REASON]
