export const AI_ORCHESTRATION_REASON = {
  REQUEST_CONFLICT: 'AI_REQUEST_ID_CONTENT_MISMATCH',
  PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  PROVIDER_INVALID_RESULT: 'AI_PROVIDER_INVALID_RESULT',
  PROVIDER_CASCADE_EXHAUSTED: 'AI_PROVIDER_CASCADE_EXHAUSTED',
} as const
