import { index, integer, jsonb, pgEnum, pgTable, text, unique, uuid } from 'drizzle-orm/pg-core'
import { tstz } from '../columns.js'

// The event inbox (PRD §17.3, §22.3, T15).
//
// THIS TABLE'S UNIQUE CONSTRAINT IS THE IDEMPOTENCY GUARANTEE. Not the service that reads it, not
// the queue, not a cache. PRD §17.3 lists `UNIQUE(event_inbox.source, event_inbox.external_event_id)`
// first, and every alternative is advisory: a check-then-insert has a window between the check and
// the insert, and two concurrent deliveries of a provider's retry both pass through it. Only the
// database can refuse. T18's accept path is built around catching that refusal, not around avoiding
// it.
//
// THE CONSTRAINT IS ON THE PAIR, deliberately. Two providers each numbering their events from 1 is
// ordinary; a constraint on external_event_id alone would silently discard the second provider's
// traffic, and the symptom would be indistinguishable from successful deduplication.
//
// WHAT "PAYLOAD MINIMIZED" MEANS HERE (§17.2). What is stored is the payload AFTER T14's schemas
// have parsed it, not the raw HTTP body. Those schemas are strict — an unmodelled field is
// rejected rather than kept — so the stored object contains only fields the platform actually
// models, and never the headers, the signature, or the bearer token that arrived with it.
//
// That is minimization, not anonymization, and the difference matters: an application.created
// payload still carries a participant's name and phone number, because replay needs them. So this
// table is in scope for §21.6 retention and for encryption at rest, which is a deployment concern
// rather than a schema one and is NOT claimed to be handled here.

/**
 * Where an event is in its lifecycle.
 *
 * An enum rather than free text because the replay path in §22.3 SELECTS by status. A typo'd
 * status is indistinguishable from a new one, and a row written as 'faild' would be invisible to
 * replay permanently — a silent, unrecoverable loss of exactly the events replay exists to rescue.
 */
export const eventInboxStatusEnum = pgEnum('event_inbox_status', [
  /** Accepted and persisted; not yet picked up. §22.3's "unprocessed inbound events". */
  'received',
  /** A worker has claimed it. Distinct from `received` so a crashed worker's rows are findable. */
  'processing',
  /** Terminal success. Replaying one of these must not repeat its side effects (§22.3). */
  'processed',
  /** Failed, retryable, and retained for replay. */
  'failed',
  /** Past the §22.4 retry limit. Still retained — dead-lettered is not deleted. */
  'dead_lettered',
])

export const eventInbox = pgTable(
  'event_inbox',
  {
    id: uuid('id').primaryKey().defaultRandom(),

    /** The producer, e.g. `helloreview_website` or `official_kakao_provider` (PRD §18.1). */
    source: text('source').notNull(),
    /** The producer's own event id. Half of the idempotency key; never generated by us. */
    externalEventId: text('external_event_id').notNull(),

    /** One of contracts' EVENT_TYPES. Text rather than an enum: adding an event type is a code
     *  change in packages/contracts, and making it a migration too would mean a schema change for
     *  every new provider capability without buying anything the T14 schema does not already. */
    eventType: text('event_type').notNull(),

    /**
     * SHA-256 of the raw request body, hex.
     *
     * Answers a question the payload cannot: "is this redelivery byte-identical to the one we
     * already accepted?" A provider that reuses an event id with CHANGED content is a bug worth
     * detecting, and without the hash it is invisible — the unique constraint would simply reject
     * the second delivery as a duplicate and the divergence would never surface.
     */
    payloadHash: text('payload_hash').notNull(),

    /**
     * The parsed, minimized payload. See the note above on what minimized means.
     *
     * Nullable: a body that fails schema validation is rejected at the edge and never reaches this
     * table, but an event accepted under a future contract version may legitimately carry none.
     */
    payload: jsonb('payload'),

    /**
     * When the producer says it happened (§18.1 occurred_at).
     *
     * NOT NULL because §22.3 requires replay to "preserve the original occurred-at time". A replay
     * that has to invent this is not a replay, and ordering — which FR-MSG-007 depends on — is
     * computed from it.
     */
    occurredAt: tstz('occurred_at').notNull(),
    /** When we accepted it. Distinct from occurredAt: the gap between them IS the delivery delay. */
    receivedAt: tstz('received_at').notNull().defaultNow(),
    /** Set once, on reaching a terminal state. Null while the event is still in flight. */
    processedAt: tstz('processed_at'),

    status: eventInboxStatusEnum('status').notNull().default('received'),

    /** How many times processing has been attempted, for the §22.4 dead-letter threshold. */
    attemptCount: integer('attempt_count').notNull().default(0),
    /**
     * Why the last attempt failed — a SCREAMING_SNAKE reason CODE, not an exception message.
     *
     * A stack trace here would be both unqueryable and a PII risk: exception messages routinely
     * interpolate the value that caused them, which for this platform is a phone number.
     */
    lastErrorReason: text('last_error_reason'),

    /** Ties every log line about this event back to the request that delivered it (§23.1). */
    correlationId: text('correlation_id'),
  },
  (table) => [
    // The whole point of the table.
    unique('event_inbox_source_external_id_key').on(table.source, table.externalEventId),

    // The replay path's only entry point (§22.3) selects by status. Without this it is a
    // sequential scan over every event ever received — fine at a hundred rows, and not the kind of
    // thing that announces itself when it stops being fine.
    index('event_inbox_status_idx').on(table.status, table.receivedAt),

    // Reconciliation and operator lookups both start from "what did this provider send us?".
    index('event_inbox_source_idx').on(table.source, table.receivedAt),

    // §23.1 makes correlation id the join key across every log line and table for one interaction.
    index('event_inbox_correlation_idx').on(table.correlationId),
  ],
)

export type EventInboxRow = typeof eventInbox.$inferSelect
export type NewEventInboxRow = typeof eventInbox.$inferInsert
