// Stable campaign-configuration reason codes (T24/T25).
//
// These cross an application boundary: publishing errors are returned to an operator surface and
// activation issues are persisted in audit detail. Prose may improve; the codes must not drift.

export const CAMPAIGN_CONFIG_REASON = {
  GUIDELINE_VERSION_NOT_FOUND: 'GUIDELINE_VERSION_NOT_FOUND',
  GUIDELINE_VERSION_NOT_DRAFT: 'GUIDELINE_VERSION_NOT_DRAFT',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_PURPOSE_INVALID: 'TEMPLATE_PURPOSE_INVALID',
  TEMPLATE_NOT_DRAFT: 'TEMPLATE_NOT_DRAFT',
  TEMPLATE_NOT_APPROVED: 'TEMPLATE_NOT_APPROVED',
  TEMPLATE_NOT_RETIRABLE: 'TEMPLATE_NOT_RETIRABLE',
  TEMPLATE_PROVIDER_APPROVAL_MISSING: 'TEMPLATE_PROVIDER_APPROVAL_MISSING',

  INVALID_CAMPAIGN_ROUTE: 'INVALID_CAMPAIGN_ROUTE',
  MISSING_RULE_VERSION: 'MISSING_RULE_VERSION',
  MISSING_RESERVATION_WINDOWS: 'MISSING_RESERVATION_WINDOWS',
  MISSING_MESSAGE_TEMPLATE: 'MISSING_MESSAGE_TEMPLATE',
  MISSING_GUIDELINE_VERSION: 'MISSING_GUIDELINE_VERSION',

  // T136 journey configuration and notification ownership.
  MISSING_APPLICATION_URL: 'MISSING_APPLICATION_URL',
  MISSING_BUSINESS_PHONE: 'MISSING_BUSINESS_PHONE',
  MISSING_BOOKING_URL: 'MISSING_BOOKING_URL',
  MISSING_SENDER_OWNERSHIP: 'MISSING_SENDER_OWNERSHIP',
  UNAUDITED_SENDER_OWNERSHIP: 'UNAUDITED_SENDER_OWNERSHIP',
  INVALID_SELECTION_POLICY: 'INVALID_SELECTION_POLICY',
} as const

export type CampaignConfigReasonCode = (typeof CAMPAIGN_CONFIG_REASON)[keyof typeof CAMPAIGN_CONFIG_REASON]
