export const SELECTION_REASON = {
  ELIGIBLE: 'ELIGIBLE',
  INELIGIBLE_LEVEL: 'INELIGIBLE_LEVEL',
  INELIGIBLE_REGION: 'INELIGIBLE_REGION',
  BELOW_VISITOR_THRESHOLD: 'BELOW_VISITOR_THRESHOLD',
  BORDERLINE_SELECTION: 'BORDERLINE_SELECTION',
  MISSING_SELECTION_POLICY: 'MISSING_SELECTION_POLICY',
  MISSING_RANKING_EVIDENCE: 'MISSING_RANKING_EVIDENCE',
  STALE_RANKING_EVIDENCE: 'STALE_RANKING_EVIDENCE',
  UNRESOLVED_REGION_MAPPING: 'UNRESOLVED_REGION_MAPPING',
  VISITOR_MEASUREMENT_PERIOD_MISMATCH: 'VISITOR_MEASUREMENT_PERIOD_MISMATCH',
  MANUAL_SELECTION: 'MANUAL_SELECTION',
  MANUAL_REVIEW_REQUIRED: 'SELECTION_MANUAL_REVIEW_REQUIRED',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
  SELECTION_REVOKED: 'SELECTION_REVOKED',
} as const

export type SelectionReasonCode = (typeof SELECTION_REASON)[keyof typeof SELECTION_REASON]
